name: Update Data
on:
  push:
    paths:
      - 'data-submodule/**'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
      - run: python process_data.py
      - name: Commit processed data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/
          git commit -m "Update processed data"
          git push
