name: Update Tag Data
on:
  push:
    paths:
      - 'data-submodule/**'
  repository_dispatch:
    types: [update_data]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # pin to v4.7.1
        with:
          python-version: '3.x'
      - run: python process_data.py
      - name: Commit processed data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/
          git commit -m "Update processed data" || echo "No changes to commit"
          git push
